// Run only against an isolated Text Studio with a test Provider and test Live manager.
(async () => {
  const checks = [];
  const check = (ok, label) => { if (!ok) throw new Error(label); checks.push(label); };
  await newProject(false);
  $('sourceText').value = '这件风衣版型比较宽松。里面可以叠穿毛衣。腰带可以按自己的需要调节。';
  await parseText();
  const sourceId = state.projectId;
  await TextStudioVariants.createCopy();
  check(state.projectId !== sourceId && state.contextGroups.length === 1, 'copy creates a separate grouped project');
  const copyId = state.projectId;
  await generalizeAll();
  check(finalReady() && state.contextGroups[0].variants.length === 3, 'HTTP generation installs complete group');
  selectCandidate(1, 1);
  check(state.paragraphs.every(p => p.selectedIndex === 1), 'candidate selection switches every member');
  editCandidate(0, '人工编辑这一版本的首句。');
  check(state.paragraphs[0].candidates[1] === '人工编辑这一版本的首句。', 'single sentence editing keeps candidate slot');
  await queueSave(true);
  await loadProject(copyId);
  check(state.paragraphs[0].editedText === '人工编辑这一版本的首句。', 'save and restore retain edit and selected variant');
  const body = {...projectPayload(), segments: liveCandidatePools()};
  check(body.context_groups.length === 1 && body.segments.every(p => p.candidates.length === 3), 'Live payload contains every complete variant');
  await api('/api/live/reset', {});
  await api('/api/live/start', body);
  await new Promise(resolve => setTimeout(resolve, 50));
  await api('/api/live/stop', {});
  const live = await apiGet('/api/live/status');
  check(live.variant_selection?.length === 1 && live.round_number === 2 && live.generated_segments === 1, 'real session selector emits complete group rounds');
  selectCandidate(0, 2);
  const safe = state.paragraphs[0].candidates[2];
  editCandidate(0, '免费试吃。');
  selectCandidate(0, 0);
  detectRisks();
  const hit = state.riskFindings.find(f => f.blocked && f.candidate_index === 2);
  check(!!hit, 'prohibited detection covers unselected variants');
  locateRiskById(hit.paragraph_id, hit.position, hit.candidate_index);
  check(state.paragraphs.every(p => p.selectedIndex === 2), 'risk location activates the correct whole variant');
  check($('exactRiskEditorText').value === '免费试吃。', 'exact risk editor shows hidden variant text');
  $('exactRiskEditorText').value = '修改后的第三套文本。';
  $('exactRiskEditorSave').click();
  check(state.paragraphs[0].candidates[2] === '修改后的第三套文本。', 'exact editor saves into correct variant slot');
  editCandidate(0, safe);
  selectCandidate(0, 1);
  const before = state.paragraphs[0].candidates[1];
  await regenerate(0);
  check(state.paragraphs[0].candidates[1] === before && !$('contextPending').hidden, 'regeneration previews without overwriting edits');
  await TextStudioVariants.applyPending();
  check(state.contextGroups[0].revision === 2 && $('contextPending').hidden, 'apply replaces the whole group atomically');
  const saved = (await apiGet('/api/project?project_id=' + copyId)).project;
  check(saved.schema_version === 2 && saved.context_groups[0].revision === 2, 'schema v2 persists group revision');
  const original = (await apiGet('/api/project?project_id=' + sourceId)).project;
  check(!original.context_groups && original.paragraphs.every(p => !p.candidates.length), 'source project remains unchanged');
  clearTimeout(state.saveTimer);
  return {passed: checks.length, checks, sourceId, copyId};
})()
