// Run only in an isolated Text Studio fixture with mock Gateway and /test-observed.
(async () => {
  const checks = [];
  const check = (ok, label) => { if (!ok) throw new Error(label); checks.push(label); };
  const waitFor = async predicate => {
    const end = Date.now() + 5000;
    while (!await predicate()) { if (Date.now() > end) throw new Error('condition timed out'); await new Promise(r => setTimeout(r, 30)); }
  };
  const sentence = '我给咱们姐妹把宠粉福利做到了，支持七天无理由，还给大家赠送运费险啊。';
  const original = sentence + '免费试吃。';
  await newProject(false);
  $('projectName').value = '人工处理禁止播报验证';
  state.paragraphs = [{id:'p1',index:1,original_text:original,candidates:[original,original],selectedIndex:0,editedText:original}];
  state.ttsReady = true;
  render(); renderRiskDrawer();
  check(broadcastText(state.paragraphs[0]) === '', 'unconfirmed claims stay blocked');
  check(document.querySelector('#para-0 .para-head-actions button').disabled, 'fully blocked preview is disabled');
  const allow = [...document.querySelectorAll('#para-0 .prohibited-sentence button')].find(b => b.textContent === '确认可播报');
  check(!!allow, 'sentence card provides manual confirmation action');
  allow.click();
  await waitFor(() => !!state.projectId && $('message').textContent.includes('本句已人工确认'));
  check(broadcastText(state.paragraphs[0]) === sentence, 'only the chosen sentence is allowed');
  check(state.riskFindings.some(f => f.approved && f.reason.includes('运费险')), 'approved finding retains original rule labels');
  check(state.riskFindings.filter(f => f.blocked).length === 1, 'other prohibited sentence stays blocked');
  check(!document.querySelector('#para-0 .para-head-actions button').disabled, 'confirmed text enables preview');
  setRiskFilter('approved');
  check($('riskResults').textContent.includes('恢复屏蔽'), 'review drawer supports revocation');
  await preview(0);
  let observed = await apiGet('/test-observed');
  check(observed.preview.at(-1).text === sentence, 'actual preview HTTP transport retains approved sentence');
  await startLive();
  await waitFor(async () => (await apiGet('/api/live/status')).status === 'stopped');
  await refreshLiveStatus();
  observed = await apiGet('/test-observed');
  check(observed.enqueued.at(-1) === sentence, 'ordinary Live synthesizes approved text');
  clearInterval(state.liveTimer); state.liveTimer = null;
  await queueSave(true);
  const projectId = state.projectId;
  await loadProject(projectId);
  check(broadcastText(state.paragraphs[0]) === sentence, 'save and reload preserve confirmation');
  const exported = TextStudioReviews.exportParagraph(state.paragraphs[0]);
  check(exported.selected_text === sentence && TextStudioProhibited.analyze(sentence, exported.prohibited_reviews).text === sentence, 'filtered JSON export retains exact confirmation with rebased offsets');
  selectCandidate(0, 1);
  check(broadcastText(state.paragraphs[0]) === '', 'identical text in another candidate is not approved');
  selectCandidate(0, 0);
  const hit = TextStudioReviews.findings().find(f => f.approved);
  await TextStudioReviews.decide(hit.paragraph_id, hit.position, hit.candidate_index, false);
  check(broadcastText(state.paragraphs[0]) === '', 'revocation restores suppression');
  await loadProject(projectId);
  check(broadcastText(state.paragraphs[0]) === '', 'revocation survives reload');
  await TextStudioReviews.decide('p1', 0, 0, true);
  editCandidate(0, '今天' + original);
  check(!state.paragraphs[0].prohibited_reviews.length && broadcastText(state.paragraphs[0]) === '', 'editing invalidates stale confirmation');
  // A sentence crossing edit-unit boundaries needs one explicit decision covering every member.
  await newProject(true);
  const parts = ['🍑支持七天无理由，', '还给大家赠送运费险啊。'];
  state.paragraphs = parts.map((text, i) => ({id:'g'+i,index:i+1,original_text:text,candidates:[text],selectedIndex:0,editedText:text}));
  state.contextGroups = (await api('/api/context/groups', {paragraphs:state.paragraphs})).context_groups;
  const group = state.contextGroups[0];
  group.revision = 1;
  group.variants = [{id:'test-v1',candidate_index:0}];
  group.selected_variant_id = 'test-v1';
  render();
  await TextStudioReviews.decide('g0', 0, 0, true);
  check(state.paragraphs.every(p => p.prohibited_reviews.length === 1), 'cross-unit sentence records confirmation for each exact member');
  check(state.paragraphs.map(broadcastText).join('') === parts.join(''), 'cross-unit approved text is visible without rewriting');
  await preview(1);
  observed = await apiGet('/test-observed');
  check(observed.preview.at(-1).text === parts[1], 'group preview preserves approved fragment using complete context');
  await startLive();
  await waitFor(async () => (await apiGet('/api/live/status')).status === 'stopped');
  await refreshLiveStatus();
  observed = await apiGet('/test-observed');
  check(observed.enqueued.at(-1) === parts.join(''), 'semantic group Live honors cross-unit human confirmation');
  clearInterval(state.liveTimer); state.liveTimer = null;
  await TextStudioReviews.decide('g1', 0, 0, false);
  check(state.paragraphs.every(p => !p.prohibited_reviews.length) && !broadcastReady(), 'revoking any member revokes the entire sentence');
  await TextStudioReviews.decide('g0', 0, 0, true);
  editCandidate(1, parts[1] + '今天有效。');
  check(!broadcastText(state.paragraphs[0]), 'changed neighbor invalidates cross-unit approval');
  check(!document.querySelector('#para-0 .approved-sentence') && document.querySelector('#para-0 .generated-preview').textContent === '本段无可播报内容。', 'editing refreshes the affected neighboring card immediately');
  clearTimeout(state.saveTimer);
  await queueSave(true);
  return {passed:checks.length,checks,projectId};
})()
